### ISSUE TITLE
How to run the DeepSmith

### ISSUE THREAD

**Issue by georgiazhang** [ChrisCummins/phd#24]
Hi,
Thanks for your great work about fuzzing with DL,
Recently, I have read your paper and want to do some work after the DeepSmith.
But I have no idea about how to run your code.
Would you mind giving me a specific tutorial？
Thank you very much!

**Comment by ChrisCummins** [comment]
Hi @georgiazhang, sure! I'm sorry it's confusing - this is still research code and not documented very well :) The process will depend very much on what you are wanting to do. If you would like to replicate the experiments of our [ISSTA'18 paper](https://chriscummins.cc/pub/2018-issta.pdf), you want to take a look at [experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz.py](https://github.com/ChrisCummins/phd/tree/master/experimental/deeplearning/deepsmith/opencl_fuzz/opencl_fuzz.py), which contains a python script for differential testing an OpenCL testbed using a pre-trained [CLgen](https://github.com/ChrisCummins/phd/tree/master/deeplearning/clgen) neural network. To run this code you must first set up the Bazel and python dependencies as described in the [README](https://github.com/ChrisCummins/phd#---building-the-code---------). There is also a pre-built [docker image](https://hub.docker.com/r/chriscummins/opencl_fuzz/) of this script you may be interested in.

If you have a specific use case, please let me know and I will do my best to guide you.

**Comment by ChrisCummins** [comment]
I'm closing this as not an "issue", but feel free to ask further questions :)

**Comment by JiajieZhang-Georgia** [comment]
Hi, Chris.
Thanks for your kind reply.
Due to some reasons, I lost behind this work for a long time.

Recently, I tried to reopen the case about generating smart contract as described in your paper  ISSTA2018.
I still feel confused about the following work, I'm so sorry to bother you again.

My goal is to reproduce the work you mentioned in the end of paper, which is using DeepSmith to verify the extensibility of solidity.

For the first step, I need to run the code for OpenCL, but I'm still not sure which one I should run. Should I follow the README file in this one? https://github.com/ChrisCummins/phd/tree/master/experimental/deeplearning/deepsmith/opencl_fuzz

For the following, I try to do as you mentioned in the issue #30 .

Sorry again, I'm so new for the work. Is it possible to get a tutorial for only solidity language?

Thank you soooo much!
